### ISSUE TITLE
`KeyError: 'datapath'` when trying to run

### ISSUE THREAD

**Issue by Freso** [j4321/Scheduler#11]
Installed from AUR. It initially failed to launch due to some dependencies still being stuck in Python 3.9 land. After going through and rebuilding/reinstalling all packages still in 3.9 land, I’m now getting this `KeyError: 'datapath'` error. I noticed that https://github.com/j4321/Scheduler/issues/10 is also a `matplotlib` based error, in case they are somehow related.

```
freso@din ~ (master)> scheduler
Quit
Traceback (most recent call last):
  File "/usr/bin/scheduler", line 84, in <module>
    from schedulerlib.scheduler import EventScheduler
  File "/usr/lib/python3.10/site-packages/schedulerlib/scheduler.py", line 50, in <module>
    from schedulerlib.widgets import EventWidget, Timer, TaskWidget, Pomodoro, CalendarWidget
  File "/usr/lib/python3.10/site-packages/schedulerlib/widgets/__init__.py", line 25, in <module>
    from .pomodoro_widget import Pomodoro
  File "/usr/lib/python3.10/site-packages/schedulerlib/widgets/pomodoro_widget.py", line 33, in <module>
    from schedulerlib.pomodoro_stats import Stats
  File "/usr/lib/python3.10/site-packages/schedulerlib/pomodoro_stats.py", line 34, in <module>
    from schedulerlib.navtoolbar import NavigationToolbar
  File "/usr/lib/python3.10/site-packages/schedulerlib/navtoolbar.py", line 45, in <module>
    class NavigationToolbar(NavigationToolbar2Tk):
  File "/usr/lib/python3.10/site-packages/schedulerlib/navtoolbar.py", line 47, in NavigationToolbar
    ('Home', _('Reset original view'), os.path.join(rcParams['datapath'], 'images', 'home.gif'), 'home'),
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 674, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'datapath'
freso@din ~ (master) [1]> ls -Ald /usr/lib/python*
drwxr-xr-x 1 root root 14056 Oct 20 15:57 /usr/lib/python2.7
drwxr-xr-x 1 root root  4086 Dec 26 20:37 /usr/lib/python3.10
```

**Comment by mathgeniuszach** [comment]
Can confirm, same exact error.
